name: SameBoy-libretro Builds
on:
  workflow_dispatch:
jobs:
  Windows:
    name: Build SameBoy-libretro
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libpng-dev
          bison
          unzip
          p7zip
    - name: Install RGBDS
    - shell: msys2 {0}
      run: |
        cd `mktemp -d`
        curl -L https://github.com/gbdev/rgbds/releases/download/v0.4.0/rgbds-0.4.0-win64.zip > rgbds.zip
        unzip rgbds.zip
        cd rgbds-*
        mv * /usr/local/bin
        cd ..
    - name: Fetch the source
    - uses: actions/checkout@v2
      run: git clone https://github.com/LIJI32/SameBoy
    - name: Build SameBoy
    - shell: msys2 {0}
      working-directory: SameBoy
      run: |
        make libretro -j8
    - name: Zip .dll
      working-directory: SameBoy/build/bin
      run: 7z a -mx=9 SameBoy-Win-x86_64.7z *.dll
    - name: Upload 7z
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: SameBoy/build/bin/SameBoy-Win-x86_64.7z
        tag: Main
        asset_name: SameBoy-Win-x86_64.7z
        overwrite: true
