name: SameBoy-libretro Builds
on:
  workflow_dispatch:
jobs:
  Windows:
    name: Build SameBoy-libretro
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-wget
          unzip
          p7zip
    - uses: actions/checkout@v2
    - name: Fetch the source
      run: git clone https://github.com/LIJI32/SameBoy
    - shell: msys2 {0}
      working-directory: SameBoy
      run: |
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/agb_boot.bin?raw=true
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/cgb0_boot.bin?raw=true
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/cgb_boot.bin?raw=true
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/dmg_boot.bin?raw=true
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/mgb_boot.bin?raw=true
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/sgb2_boot.bin?raw=true
        wget https://github.com/LIJI32/SameBoy/blob/libretro/BootROMs/prebuilt/sgb_boot.bin?raw=true
        mkdir -p build/bin/BootROMs
        mv *.bin build/bin/BootROMs
        cd libretro
        make -j8
    - name: Zip .dll
      working-directory: SameBoy/build/bin
      run: 7z a -mx=9 SameBoy-libretro-Win-x86_64.7z *.dll
    - name: Upload 7z
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: SameBoy/build/bin/SameBoy-libretro-Win-x86_64.7z
        tag: Main
        asset_name: SameBoy-libretro-Win-x86_64.7z
        overwrite: true
